server:
  port: 8080

spring:
  application:
    name: clean-photo

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    com.cleanphoto: DEBUG
    org.springframework.web: INFO
